ers/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('event.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

event/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'event'

urlpatterns = [
    path('', views.EventIndexView.as_view(), name='index'),
    path('events/<int:pk>/', views.EventDetailView.as_view(), name='detail'),
    path('register/', views.user_register, name='user-register'),
    path('register/completed/', views.completed_register, name='complete'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

event/models.py
from django.db import models
from django.forms import ModelForm
from django.utils import timezone
from . import script

# Create your models here.


class Event(models.Model):
    name = models.CharField(
        max_length=200,
        verbose_name='نام رویداد',
    )

    location = models.CharField(
        max_length=200,
        verbose_name='مکان',
    )

    date_fa = models.CharField(
        max_length=100,
        verbose_name='تاریخ فارسی',
        default='آخر این هفته'
    )

    date = models.DateTimeField(
        verbose_name='زمان',
    )

    duration = models.IntegerField(
        verbose_name='مدت/ روز',
        default=1,
    )

    price = models.CharField(
        max_length=100,
        default='رایگان',
        verbose_name='هزینه ثبت نام/ تومان',
    )

    desc = models.TextField(
        verbose_name='توضیحات بیشتر',
        blank=True,
    )

    lat = models.FloatField(
        blank=True,
        null=True,
        verbose_name='عرض جغرافیایی',
    )

    lng = models.FloatField(
        blank=True,
        null=True,
        verbose_name='طول جغرافیایی',
    )

    pic = models.ImageField(
        upload_to='event/',
        verbose_name='تصویر',
        max_length=500,
        )
    picv = models.ImageField(
        upload_to='event/',
        verbose_name='تصویر-عمودی',
        max_length=500,
        blank=True,
        null=True,
        )

    created = models.DateTimeField(
        auto_now_add=timezone.now,
        editable=False,
        verbose_name='زمان ثبت',
    )

    last_modified = models.DateTimeField(
        auto_now=timezone.now,
        verbose_name='آخرین تغییر',
    )

    class Meta:
        ordering = ('date',)

    def __str__(self):
        return self.name


class User(models.Model):
    event = models.ManyToManyField(
        Event,
        verbose_name='رویداد ها',
    )

    name = models.CharField(
        max_length=200,
        verbose_name='نام و نام خانوادگی',
    )

    tell = models.CharField(
        max_length=13,
        verbose_name='شماره تلفن همراه',
    )

    email = models.EmailField(
        blank=True,
        verbose_name='پست الکترونیک',
    )

    age = models.IntegerField(
        verbose_name='سن',
        )

    address = models.CharField(
        max_length=300,
        blank=True,
        verbose_name='آدرس',
    )

    desc = models.TextField(
        verbose_name='توضیحات اضافه',
        blank=True,
    )

    created = models.DateTimeField(
        auto_now_add=timezone.now,
        editable=False,
        verbose_name='زمان ثبت',
    )

    last_modified = models.DateTimeField(
        auto_now=timezone.now,
        verbose_name='آخرین تغییر',
    )

    class Meta:
        ordering = ('-last_modified',)

    def __str__(self):
        return self.name

event/forms.py
from django import forms
from . import models


class UserForm(forms.ModelForm):
    class Meta:
        model = models.User
        fields = ('event', 'name', 'tell', 'age')
        # exclude = []
        widgets = {
            'event': forms.CheckboxSelectMultiple,
        }

event/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.views import generic
from . import models
from . import forms

# Create your views here.


class EventIndexView(generic.ListView):
    template_name = 'event/index.html'
    context_object_name = 'events'

    def get_queryset(self):
        return models.Event.objects.order_by('date')


class EventDetailView(generic.DetailView):
    template_name = 'event/detail.html'
    model = models.Event


def user_register(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = forms.UserForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            form.save()
            # redirect to a new URL:
            return HttpResponseRedirect('completed/')

    # if a GET (or any other method) we'll create a blank form
    else:
        form = forms.UserForm()

    return render(request, 'event/register.html', {'form': form})


def completed_register(request):
    new_user = forms.UserForm(request.POST)
    # if new_user.is_valid():
    #    new_user.save()
    return render(request, 'event/completed.html', {'user': new_user})

event/templates/ers/detail.html
{% if event %}
    <p>
        <h2>
            {{ event.date }}
        </h2>
        <p>
        موقعیت : {{ event.location }}
        </p>
        <p>
            زمان : {{ event.date }} - {{ event.duration }} روزه
        </p>
        {% if event.desc %}
            <p>
                <h4>
                    توضیحات
                </h4>
                {{ event.desc}}
            </p>
        {% endif %}
    </p>
{% else %}
    <p>
        not Event found
    </p>
{% endif %}

<a href="{% url 'event:index' %}">بازگشت</a>

event/templates/ers/index.html
{% if events %}
    <h2>رویدادهای پیش رو</h2>
    <ul>
        {% for event in events %}
    <li>
        <a href="{{ event.pk }}">{{ event }}</a>
        <p>
            {{ event.date }} - {{ event.duration }} روزه    <br>
            <a href="{{ event.pk }}">اظلاعات بیشتر</a>
        </p>
    </li>
    {% endfor %}
    </ul>
{% else %}
    <p>
        Sorry... Not any Event found
    </p>
{% endif %}

event/templates/event/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>
            {% block title %}
                تور بُ
            {% endblock %}
        </title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static 'event/css/bootstrap.css' %}">
        <link rel="stylesheet" href="{% static 'event/css/main.css' %}">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
        <script src="{% static 'event/js/script.js' %}"></script>
        <script src="https://kit.fontawesome.com/ce3be143e1.js"></script>
        {% block head %}    {% endblock %}
    </head>

    <body>

        <header>
            {% block nav %}     {% endblock %}
        </header>

        <section>
            <header>
                {% block sec-header %}  {% endblock %}
            </header>
            <div class="clearfix"></div>
            <article>
                {% block article %}     {% endblock %}
            </article>
            <div class="clearfix"></div>
            <footer>
                {% block sec-footer %}  {% endblock %}
            </footer>
        </section>

        <footer>
            {% block footer %}  {% endblock %}
        </footer>

    </body>
</html>

event/templates/event/carousel.html
<div class="container-fluid">
  <div class="row">
    <div id="demo" class="carousel slide" data-ride="carousel">
            <ul class="carousel-indicators">
              {% for event in events %}
                {% if forloop.first %}
              <li data-target="#demo" data-slide-to="{{ forloop.counter0 }}" class="active"></li>
                {% else %}
              <li data-target="#demo" data-slide-to="{{ forloop.counter0 }}"></li>
                {% endif %}
              {% endfor %}
            </ul>
            <div class="carousel-inner">

                {% for event in events %}

                    {% if forloop.first %}
              <div class="carousel-item active">
                <picture>
                    <source srcset="{{ event.pic.url }}" media="(orientation: landscape)">
                        {% if event.picv %}
                    <source srcset="{{ event.picv.url }}">
                        {% endif %}
                    <img srcset="{{ event.pic.url }}" alt="{{ event.name }}" width="100%" class="img-full">
                </picture>

                <div class="carousel-caption">
                  <h3>{{ event.name }} - {{ event.duration }} روزه</h3>
                  <p>{{ event.location}} | {{ event.date_fa }}</p>
                  <p>
                    <a href="events/{{ event.pk }}" class='btn btn-primary'>مشاهده جزییات</a> &nbsp; 
                    <a href="{% url 'event:user-register' %}" class="btn btn-danger">ثبت نام</a>
                  </p> 
                </div>   
              </div>
              
                  {% else %}
                
              <div class="carousel-item">
                <picture>
                    <source srcset="{{ event.pic.url }}" media="(orientation: landscape)">
                        {% if event.picv %}
                    <source srcset="{{ event.picv.url }}">
                        {% endif %}
                    <img srcset="{{ event.pic.url }}" alt="{{ event.name }}" width="100%" class="img-full">
                </picture>
                
                <div class="carousel-caption">
                  <h3>{{ event.name }} - {{ event.duration }} روزه</h3>
                  <p>{{ event.location}} | {{ event.date_fa }}</p>
                  <p>
                    <a href="events/{{ event.pk }}" class='btn btn-primary'>مشاهده جزییات</a> &nbsp; 
                    <a href="{% url 'event:user-register' %}" class="btn btn-danger">ثبت نام</a>
                  </p>  
                </div>   
              </div>

                  {% endif %}
                {% endfor %}

            </div>
            <a class="carousel-control-prev" href="#demo" data-slide="prev">
                <span class="carousel-control-next-icon"></span>
            </a>
            <a class="carousel-control-next" href="#demo" data-slide="next">
              <span class="carousel-control-prev-icon"></span>
            </a>
    </div>
  </div>
</div>

event/templates/event/completed.html
{% extends 'event/base.html' %}

{% block title%}
    پایان ثبت نام
{% endblock %}


{% block nav %}
    {% include 'event/nav.html' %}
{% endblock %}


{% block article %}
    <div class="article-main">
        <div class="container">
            <div class="row">
                <div class="col-md-12 register-head full-view">
                        <h2>
                            تبریک!  <br><br>
                            ثبت نام شما با موفقیت به پایان رسید.    
                        </h2>
                        <p><br><br>
                            مشخصات شما در سیستم ثبت شد.
                            
                        </p>
                        <p><br>
                            <a href="{% url 'event:index' %}" class="btn btn-info">بازگشت به صفحه اصلی</a>
                        </p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}


{% block footer %}
    {% include 'event/footer.html' %}
{% endblock %}

event/templates/event/detail.html
{% extends 'event/base.html' %}

{% if event %}

{% block title %}
    تور بُ - {{ event.name }}
{% endblock %}

{% block nav %}
    {% include 'event/nav.html' %}
{% endblock %}

{% block article %}
<div class='article-main'>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-4 article-box">
                <p>
                    <h2>
                        {{ event.name }}
                    </h2>
                </p>
                <p>
                    <h4>
                        <i class="fas fa-map-marked-alt"></i> &nbsp;&nbsp; {{ event.location }}
                    </h4>
                </p>
                <p><br>
                    <i class="fas fa-calendar-alt"></i> &nbsp;&nbsp; {{ event.date_fa }}
                </p>
                <p>
                    <i class="fas fa-bell"></i>  &nbsp;&nbsp; {{ event.duration }} روزه
                </p>
                <h4 style='color:red;'>
                    <i class="fas fa-credit-card"></i> &nbsp;&nbsp; {{ event.price }} تومان
                </h4><br>
                <a href="{% url 'event:user-register' %}" class="btn btn-warning btn-block"> ثبت نام </a>
            </div>
            <div class="col-md-4 article-box">
                {% if event.desc %}
                <h4>
                    توضیحات بیشتر
                </h4>
                <p>
                    {{ event.desc|linebreaks }}
                </p>
                {% endif %}
            </div>
                {% if event.lat %}
                {% if event.lng %}
            <div id="googleMap" class="col-md-4 article-box">
                <script>
                    function myMap() {
                    var mapProp= {
                        center:new google.maps.LatLng({{ event.lat }},{{ event.lng}}),
                        zoom:5,
                    };
                    var map = new google.maps.Map(document.getElementById("googleMap"),mapProp);
                    }
                </script>    
                <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAggmQ-HNol_aJcWNmaU2jv9WIc57__bhc&callback=myMap"></script>
                {% endif %}
                {% endif %}
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="row row-pic">
            <div class="col-md-12">
                
                    <div class="album-row">
                            <div class="album-column">
                              <img src="{{ event.pic.url}}" class="img-fit" alt="{{ event.name}}" onclick="myFunction(this);">
                            </div>
                        {% if event.picv %}
                            <div class="album-column">
                              <img src="{{ event.picv.url }}" class="img-fit"  alt="{{ event.name }}" onclick="myFunction(this);">
                            </div>
                        {% endif %}
                    </div>  
                          <!-- The expanding image container -->
                          <div class="album-container">
                            <!-- Close the image -->
                            <span onclick="this.parentElement.style.display='none'" class="album-closebtn">&times;</span>
                            <!-- Expanded image -->
                            <img id="expandedImg" class ="img-prev img-fit">
                            <!-- Image text -->
                            <div id="album-imgtext"></div>
                          </div>
            </div>
        </div>
    </div>    
</div>
{% endblock %}

{% block footer %}
    {% include 'event/footer.html' %}
{% endblock %}

{% endif %}

event/templates/event/footer.html
<div class="footer-social">
    <div class="container">
        <div class="row">

            <div class="col-md-12">
                <a href="https://instagram.com/tour.beau/">
                    <i class="fab fa-instagram fa-2x"></i>
                </a>
                <a href="https://t.me/tourbeau/">
                    <i class="fab fa-telegram fa-2x"></i>
                </a>
            </div>
            
        </div>
    </div>
</div>

<div class="clearfix"></div>

<div class="container-fluid">
    <div class="row">
        <div class="col-md-4 footer-box">
            <h3>ارتباط با ما</h3>
            <p>
                <i class="fas fa-map-marker-alt"></i>&nbsp;&nbsp;
                بابل - خیابان شریعتی - خیابان گل - گل 2 - کافه بُ   <br>
                <i class="fas fa-phone-square"></i>&nbsp;&nbsp;
                09117448583     <br>
                <i class="fas fa-envelope"></i>&nbsp;&nbsp;
                info@tourbeau.ir
            </p>
        </div>
        <div class="col-md-4 footer-box">
            <h3><i class="fas fa-users"></i></h3>
            <p>
                در شبکه های اجتماعی با هشتگ
                we_are_beau
                ما را دنبال کنید.
            </p>
        </div>
        <div class="col-md-4 footer-box">
            <h3><i class="fab fa-git-alt"></i></h3>
            <p>
                این پروژه تحت پروانه ی عمومی همگانی گنو "GNU General Public License v3.0" منتشر شده است.    <br>
                <a href="https://github.com/iamrf/ERS/" class="btn btn-dark">
                    <i class="fab fa-github"></i> مشارکت در پروژه
                </a>
            </p>
        </div>
    </div>
</div>

<div class="clearfix"></div>

<div class="footer-iamrf">
    <div class="container">
        <div class="row">
            <div class="col-12">
                Designed by <a href="https://iamrf.net/">iamrf</a> - All rights reserved <i class="fas fa-copyright"></i> 2018-{% now "y" %}
            </div>
        </div>
    </div>
</div>

event/templates/event/index.html
{% extends 'event/base.html' %}

{% block title %}
    تور بُ - رویداد ها
{% endblock %}


{% block nav %}
  {% include 'event/nav.html' %}
{% endblock %}


{% block article %}

    {% if events %}         
      <!--    carousel    -->
        {% include 'event/carousel.html' %}
      <!--    End carousel    -->
    {% else %}
      <p>
          <h2>
              متاسفانه هیج رویدادی یافت نشد...
          </h2>
      </p>
    {% endif %}

{% endblock %}


{% block footer %}
  {% include 'event/footer.html' %}
{% endblock %}

event/templates/event/nav.html
<nav class="navbar navbar-expand-md bg-light navbar-light">
  <!-- Brand -->
  <a class="navbar-brand" href="{% url 'event:index' %}">تور بُ</a>

  <!-- Toggler/collapsibe Button -->
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
    <span class="navbar-toggler-icon"></span>
  </button>

  <!-- Navbar links -->
  <div class="collapse navbar-collapse" id="collapsibleNavbar">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'event:user-register' %}">ثبت نام</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">تخفیف</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">درباره تور بُ</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
          راهنما
        </a>
        <div class="dropdown-menu">
          <a class="dropdown-item" href="{% url 'event:user-register' %}">راهنمای ثبت نام</a>
          <a class="dropdown-item" href="https://instagram.com/tour.beau/"><i class="fab fa-instagram"></i>&nbsp;اینستاگرام</a>
          <a class="dropdown-item" href="https://t.me/tourbeau/"><i class="fab fa-telegram-plane"></i>&nbsp;تلگرام</a>
        </div>
      </li>
    </ul>
  </div>
</nav>

event/templates/event/raw.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>
            /Title
        </title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
        <link rel="stylesheet" href="{% static 'event/css/main.css' %}">
    </head>
    <body>
        <section>
            <header>
                
            </header>
            <article>
                
            </article>
            <footer>

            </footer>
        </section>
        
    </body>
</html>

event/templates/event/register.html
{% extends 'event/base.html' %}

{% block title %}
    تور بُ - ثبت نام رویداد
{% endblock %}

{% block nav %}
    {% include 'event/nav.html' %}
{% endblock %}

{% block article %}
    <div class="article-main register">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <div class="register-head"><h1>ثبت نام در رویداد</h1></div>
                
                    <form action="" method="post">
                        {% csrf_token %}
                        {% for field in form %}
                        <p>
                            {{ field.errors }}
                            {{ field.label_tag }} <br> {{ field }}
                            {% if field.help_text %}
                            <p class="help">{{ field.help_text|safe }}</p>
                            {% endif %}
                        </p>
                        {% endfor %}
                        <input type="submit" value="ثبت نام" class="btn btn-danger btn-block">
                    </form>
                
                </div>
                <div class="col-md-6">
                    <div class="register-head" id="register-help">
                        <h2>راهنمای ثبت نام</h2>
                    </div>
                    <p>
                        * ابتدا رویدادی که قصد ثبت نام در آن دارید را انتخاب نمایید (انتخاب چند گزینه مجاز می باشد). <br>
                        * نام و نام خانوادگی خود را ترجیحا به فارسی وارد نمایید.    <br>
                        * سن خود را وارد کنید.  <br>
                        <span style='color:red;'>* پر کردن همه گزینه های مذکور اجباری است.</span>
                    </p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block footer %}
    {% include 'event/footer.html' %}
{% endblock %}